#!/bin/bash
# =============================================================================
# extract-to-public.sh — extrai sub-projeto de monorepo privado pra repo público.
# =============================================================================
# Workflow padronizado para extração SEGURA, evitando vazamento de histórico
# privado, IPs internos, paths de monorepo, etc.
#
# 4 fases:
#   1. Worktree isolado — não suja main do monorepo privado
#   2. Sanitize sweep — scripts/sanitize-check.js bloqueia se houver match
#   3. Squash em branch órfão — zero histórico contaminado
#   4. Force-push pro repo público — idealmente recém-criado vazio
#
# Uso:
#   bash scripts/extract-to-public.sh \
#     --src-dir tektus-agent-os \
#     --target-remote https://github.com/Org/public-repo.git \
#     --branch main
#
# Requisitos:
#   - estar dentro de um clone git
#   - .sanitize-patterns.yaml configurado com seus IPs/nomes/paths privados
#   - scripts/sanitize-check.js disponível
# =============================================================================

set -euo pipefail

# ---------- args ----------
SRC_DIR=""
TARGET_REMOTE=""
BRANCH="main"
WORKTREE_PATH=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --src-dir) SRC_DIR="$2"; shift 2 ;;
    --target-remote) TARGET_REMOTE="$2"; shift 2 ;;
    --branch) BRANCH="$2"; shift 2 ;;
    --worktree) WORKTREE_PATH="$2"; shift 2 ;;
    *) echo "Flag desconhecida: $1"; exit 1 ;;
  esac
done

if [[ -z "$SRC_DIR" || -z "$TARGET_REMOTE" ]]; then
  echo "Uso: $0 --src-dir <path> --target-remote <git url> [--branch main]"
  exit 1
fi

WORKTREE_PATH="${WORKTREE_PATH:-${SRC_DIR}-extract-public}"

# ---------- Fase 1: worktree ----------
log() { echo -e "\n\033[1;36m[$(date +%H:%M:%S)] $*\033[0m"; }

log "=== Fase 1/4 — Worktree isolado ==="
if git worktree list | grep -q "$WORKTREE_PATH"; then
  log "Worktree já existe em $WORKTREE_PATH — usando."
else
  git worktree add "$WORKTREE_PATH" -b "extract/${SRC_DIR}-public-$(date +%Y%m%d)" 2>&1
  cp -r "$SRC_DIR/." "$WORKTREE_PATH/"
fi

cd "$WORKTREE_PATH"

# ---------- Fase 2: sanitize sweep ----------
log "=== Fase 2/4 — Sanitize sweep ==="
if [[ -f scripts/sanitize-check.js ]]; then
  if ! node scripts/sanitize-check.js --severity medium; then
    log "✗ Sanitize check falhou. Edite arquivos ou .sanitize-patterns.yaml e rode de novo."
    exit 1
  fi
else
  log "⚠ scripts/sanitize-check.js não encontrado no worktree. Pulando — RECOMENDO copiar antes."
  read -p "Continuar mesmo assim? (yes/no): " confirm
  [[ "$confirm" == "yes" ]] || exit 1
fi

# ---------- Fase 3: squash em branch órfão ----------
log "=== Fase 3/4 — Squash em branch órfão ==="
git checkout --orphan clean-main
git add -A
git commit -m "Initial commit — public release

Generated by scripts/extract-to-public.sh from internal monorepo.
Sanitize check passed: zero leaks of IPs, paths, names or secrets."

# ---------- Fase 4: sanity pós-squash + force push ----------
log "=== Fase 4/4 — Sanity pós-squash + force-push ==="
node scripts/sanitize-check.js --severity medium

# Adicionar remote se não existir
if ! git remote | grep -q "^public$"; then
  git remote add public "$TARGET_REMOTE"
fi

log "Pronto pra force-push em '$TARGET_REMOTE' ($BRANCH)."
read -p "Confirmar force-push? (yes/no): " confirm
[[ "$confirm" == "yes" ]] || { log "Abortado pelo usuário. Worktree em $WORKTREE_PATH preservado."; exit 0; }

git push --force public clean-main:"$BRANCH"
log "✓ Push concluído. Repo público: $TARGET_REMOTE ($BRANCH)"
log "Worktree em $WORKTREE_PATH — apague quando quiser com 'git worktree remove'."
