#!/usr/bin/env node
/**
 * install-hooks.js — instala git hooks locais (pre-commit + pre-push).
 *
 * Idempotente — pode rodar várias vezes. Cria `.git/hooks/pre-commit` e
 * `.git/hooks/pre-push` que invocam `scripts/sanitize-check.js`.
 *
 * Uso:
 *   node scripts/install-hooks.js
 *
 * Para desabilitar temporariamente:
 *   SANITIZE_SKIP=1 git commit ...
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

function repoRoot() {
  try {
    return execSync('git rev-parse --show-toplevel', { encoding: 'utf8' }).trim();
  } catch {
    console.error('✗ Não está dentro de um repo git.');
    process.exit(1);
  }
}

const root = repoRoot();
const hooksDir = path.join(root, '.git', 'hooks');

if (!fs.existsSync(hooksDir)) {
  console.error(`✗ ${hooksDir} não existe.`);
  process.exit(1);
}

const PRE_COMMIT = `#!/bin/sh
# Auto-generated by scripts/install-hooks.js
# Bloqueia commit se sanitize-check encontrar vazamentos em arquivos staged.
node scripts/sanitize-check.js --staged --severity medium
exit $?
`;

const PRE_PUSH = `#!/bin/sh
# Auto-generated by scripts/install-hooks.js
# Bloqueia push se sanitize-check encontrar vazamentos no tree completo.
node scripts/sanitize-check.js --severity medium
exit $?
`;

function writeHook(name, content) {
  const target = path.join(hooksDir, name);
  fs.writeFileSync(target, content, { mode: 0o755 });
  console.log(`✓ ${name} instalado em ${target}`);
}

writeHook('pre-commit', PRE_COMMIT);
writeHook('pre-push', PRE_PUSH);
console.log('\n✓ Git hooks instalados. Pra bypass de emergência: SANITIZE_SKIP=1 git commit ...');
